# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cshao/compression_project/video_phahn/video

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cshao/compression_project/video_phahn/video

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cshao/compression_project/video_phahn/video/CMakeFiles /home/cshao/compression_project/video_phahn/video/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cshao/compression_project/video_phahn/video/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Panoptes_Stage_Control

# Build rule for target.
Panoptes_Stage_Control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Panoptes_Stage_Control
.PHONY : Panoptes_Stage_Control

# fast build rule for target.
Panoptes_Stage_Control/fast:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/build
.PHONY : Panoptes_Stage_Control/fast

#=============================================================================
# Target rules for targets named Tcl_Linkvar

# Build rule for target.
Tcl_Linkvar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tcl_Linkvar
.PHONY : Tcl_Linkvar

# fast build rule for target.
Tcl_Linkvar/fast:
	$(MAKE) -f CMakeFiles/Tcl_Linkvar.dir/build.make CMakeFiles/Tcl_Linkvar.dir/build
.PHONY : Tcl_Linkvar/fast

#=============================================================================
# Target rules for targets named add_noise_to_image

# Build rule for target.
add_noise_to_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add_noise_to_image
.PHONY : add_noise_to_image

# fast build rule for target.
add_noise_to_image/fast:
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/build
.PHONY : add_noise_to_image/fast

#=============================================================================
# Target rules for targets named airy_maker

# Build rule for target.
airy_maker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 airy_maker
.PHONY : airy_maker

# fast build rule for target.
airy_maker/fast:
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/build
.PHONY : airy_maker/fast

#=============================================================================
# Target rules for targets named average_videos

# Build rule for target.
average_videos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 average_videos
.PHONY : average_videos

# fast build rule for target.
average_videos/fast:
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/build
.PHONY : average_videos/fast

#=============================================================================
# Target rules for targets named base_camera_server_library

# Build rule for target.
base_camera_server_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base_camera_server_library
.PHONY : base_camera_server_library

# fast build rule for target.
base_camera_server_library/fast:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/build
.PHONY : base_camera_server_library/fast

#=============================================================================
# Target rules for targets named check_found_spots

# Build rule for target.
check_found_spots: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_found_spots
.PHONY : check_found_spots

# fast build rule for target.
check_found_spots/fast:
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/build
.PHONY : check_found_spots/fast

#=============================================================================
# Target rules for targets named cismm_video_optimizer

# Build rule for target.
cismm_video_optimizer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cismm_video_optimizer
.PHONY : cismm_video_optimizer

# fast build rule for target.
cismm_video_optimizer/fast:
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/build
.PHONY : cismm_video_optimizer/fast

#=============================================================================
# Target rules for targets named compare_tracking_files

# Build rule for target.
compare_tracking_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compare_tracking_files
.PHONY : compare_tracking_files

# fast build rule for target.
compare_tracking_files/fast:
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/build
.PHONY : compare_tracking_files/fast

#=============================================================================
# Target rules for targets named csv_to_xml

# Build rule for target.
csv_to_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csv_to_xml
.PHONY : csv_to_xml

# fast build rule for target.
csv_to_xml/fast:
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/build
.PHONY : csv_to_xml/fast

#=============================================================================
# Target rules for targets named file_stack_library

# Build rule for target.
file_stack_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_stack_library
.PHONY : file_stack_library

# fast build rule for target.
file_stack_library/fast:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/build
.PHONY : file_stack_library/fast

#=============================================================================
# Target rules for targets named invert_image

# Build rule for target.
invert_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 invert_image
.PHONY : invert_image

# fast build rule for target.
invert_image/fast:
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/build
.PHONY : invert_image/fast

#=============================================================================
# Target rules for targets named make_compression_video

# Build rule for target.
make_compression_video: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_compression_video
.PHONY : make_compression_video

# fast build rule for target.
make_compression_video/fast:
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/build
.PHONY : make_compression_video/fast

#=============================================================================
# Target rules for targets named make_moving_spot_video

# Build rule for target.
make_moving_spot_video: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_moving_spot_video
.PHONY : make_moving_spot_video

# fast build rule for target.
make_moving_spot_video/fast:
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/build
.PHONY : make_moving_spot_video/fast

#=============================================================================
# Target rules for targets named make_multi_spot_test

# Build rule for target.
make_multi_spot_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_multi_spot_test
.PHONY : make_multi_spot_test

# fast build rule for target.
make_multi_spot_test/fast:
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/build
.PHONY : make_multi_spot_test/fast

#=============================================================================
# Target rules for targets named make_test_image

# Build rule for target.
make_test_image: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_test_image
.PHONY : make_test_image

# fast build rule for target.
make_test_image/fast:
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/build
.PHONY : make_test_image/fast

#=============================================================================
# Target rules for targets named spot_tracker_library

# Build rule for target.
spot_tracker_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spot_tracker_library
.PHONY : spot_tracker_library

# fast build rule for target.
spot_tracker_library/fast:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/build
.PHONY : spot_tracker_library/fast

#=============================================================================
# Target rules for targets named stocc_random_number_generator_library

# Build rule for target.
stocc_random_number_generator_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stocc_random_number_generator_library
.PHONY : stocc_random_number_generator_library

# fast build rule for target.
stocc_random_number_generator_library/fast:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/build
.PHONY : stocc_random_number_generator_library/fast

#=============================================================================
# Target rules for targets named swap_ppm_lines

# Build rule for target.
swap_ppm_lines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swap_ppm_lines
.PHONY : swap_ppm_lines

# fast build rule for target.
swap_ppm_lines/fast:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/build
.PHONY : swap_ppm_lines/fast

#=============================================================================
# Target rules for targets named test_spot_tracker

# Build rule for target.
test_spot_tracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_spot_tracker
.PHONY : test_spot_tracker

# fast build rule for target.
test_spot_tracker/fast:
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/build
.PHONY : test_spot_tracker/fast

#=============================================================================
# Target rules for targets named video_imager_server

# Build rule for target.
video_imager_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video_imager_server
.PHONY : video_imager_server

# fast build rule for target.
video_imager_server/fast:
	$(MAKE) -f CMakeFiles/video_imager_server.dir/build.make CMakeFiles/video_imager_server.dir/build
.PHONY : video_imager_server/fast

#=============================================================================
# Target rules for targets named video_spot_tracker

# Build rule for target.
video_spot_tracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video_spot_tracker
.PHONY : video_spot_tracker

# fast build rule for target.
video_spot_tracker/fast:
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/build
.PHONY : video_spot_tracker/fast

#=============================================================================
# Target rules for targets named video_spot_tracker_nogui

# Build rule for target.
video_spot_tracker_nogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 video_spot_tracker_nogui
.PHONY : video_spot_tracker_nogui

# fast build rule for target.
video_spot_tracker_nogui/fast:
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/build
.PHONY : video_spot_tracker_nogui/fast

#=============================================================================
# Target rules for targets named vrpn_imager_library

# Build rule for target.
vrpn_imager_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vrpn_imager_library
.PHONY : vrpn_imager_library

# fast build rule for target.
vrpn_imager_library/fast:
	$(MAKE) -f CMakeFiles/vrpn_imager_library.dir/build.make CMakeFiles/vrpn_imager_library.dir/build
.PHONY : vrpn_imager_library/fast

#=============================================================================
# Target rules for targets named xml_tracking_compare

# Build rule for target.
xml_tracking_compare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_tracking_compare
.PHONY : xml_tracking_compare

# fast build rule for target.
xml_tracking_compare/fast:
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/build
.PHONY : xml_tracking_compare/fast

Panoptes_Stage_Control.o: Panoptes_Stage_Control.cpp.o
.PHONY : Panoptes_Stage_Control.o

# target to build an object file
Panoptes_Stage_Control.cpp.o:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/Panoptes_Stage_Control.cpp.o
.PHONY : Panoptes_Stage_Control.cpp.o

Panoptes_Stage_Control.i: Panoptes_Stage_Control.cpp.i
.PHONY : Panoptes_Stage_Control.i

# target to preprocess a source file
Panoptes_Stage_Control.cpp.i:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/Panoptes_Stage_Control.cpp.i
.PHONY : Panoptes_Stage_Control.cpp.i

Panoptes_Stage_Control.s: Panoptes_Stage_Control.cpp.s
.PHONY : Panoptes_Stage_Control.s

# target to generate assembly for a file
Panoptes_Stage_Control.cpp.s:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/Panoptes_Stage_Control.cpp.s
.PHONY : Panoptes_Stage_Control.cpp.s

Tcl_Linkvar.o: Tcl_Linkvar.C.o
.PHONY : Tcl_Linkvar.o

# target to build an object file
Tcl_Linkvar.C.o:
	$(MAKE) -f CMakeFiles/Tcl_Linkvar.dir/build.make CMakeFiles/Tcl_Linkvar.dir/Tcl_Linkvar.C.o
.PHONY : Tcl_Linkvar.C.o

Tcl_Linkvar.i: Tcl_Linkvar.C.i
.PHONY : Tcl_Linkvar.i

# target to preprocess a source file
Tcl_Linkvar.C.i:
	$(MAKE) -f CMakeFiles/Tcl_Linkvar.dir/build.make CMakeFiles/Tcl_Linkvar.dir/Tcl_Linkvar.C.i
.PHONY : Tcl_Linkvar.C.i

Tcl_Linkvar.s: Tcl_Linkvar.C.s
.PHONY : Tcl_Linkvar.s

# target to generate assembly for a file
Tcl_Linkvar.C.s:
	$(MAKE) -f CMakeFiles/Tcl_Linkvar.dir/build.make CMakeFiles/Tcl_Linkvar.dir/Tcl_Linkvar.C.s
.PHONY : Tcl_Linkvar.C.s

VRPN_Imager_camera_server.o: VRPN_Imager_camera_server.cpp.o
.PHONY : VRPN_Imager_camera_server.o

# target to build an object file
VRPN_Imager_camera_server.cpp.o:
	$(MAKE) -f CMakeFiles/vrpn_imager_library.dir/build.make CMakeFiles/vrpn_imager_library.dir/VRPN_Imager_camera_server.cpp.o
.PHONY : VRPN_Imager_camera_server.cpp.o

VRPN_Imager_camera_server.i: VRPN_Imager_camera_server.cpp.i
.PHONY : VRPN_Imager_camera_server.i

# target to preprocess a source file
VRPN_Imager_camera_server.cpp.i:
	$(MAKE) -f CMakeFiles/vrpn_imager_library.dir/build.make CMakeFiles/vrpn_imager_library.dir/VRPN_Imager_camera_server.cpp.i
.PHONY : VRPN_Imager_camera_server.cpp.i

VRPN_Imager_camera_server.s: VRPN_Imager_camera_server.cpp.s
.PHONY : VRPN_Imager_camera_server.s

# target to generate assembly for a file
VRPN_Imager_camera_server.cpp.s:
	$(MAKE) -f CMakeFiles/vrpn_imager_library.dir/build.make CMakeFiles/vrpn_imager_library.dir/VRPN_Imager_camera_server.cpp.s
.PHONY : VRPN_Imager_camera_server.cpp.s

add_noise_to_image.o: add_noise_to_image.cpp.o
.PHONY : add_noise_to_image.o

# target to build an object file
add_noise_to_image.cpp.o:
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/add_noise_to_image.cpp.o
.PHONY : add_noise_to_image.cpp.o

add_noise_to_image.i: add_noise_to_image.cpp.i
.PHONY : add_noise_to_image.i

# target to preprocess a source file
add_noise_to_image.cpp.i:
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/add_noise_to_image.cpp.i
.PHONY : add_noise_to_image.cpp.i

add_noise_to_image.s: add_noise_to_image.cpp.s
.PHONY : add_noise_to_image.s

# target to generate assembly for a file
add_noise_to_image.cpp.s:
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/add_noise_to_image.cpp.s
.PHONY : add_noise_to_image.cpp.s

airy_maker.o: airy_maker.cpp.o
.PHONY : airy_maker.o

# target to build an object file
airy_maker.cpp.o:
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/airy_maker.cpp.o
.PHONY : airy_maker.cpp.o

airy_maker.i: airy_maker.cpp.i
.PHONY : airy_maker.i

# target to preprocess a source file
airy_maker.cpp.i:
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/airy_maker.cpp.i
.PHONY : airy_maker.cpp.i

airy_maker.s: airy_maker.cpp.s
.PHONY : airy_maker.s

# target to generate assembly for a file
airy_maker.cpp.s:
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/airy_maker.cpp.s
.PHONY : airy_maker.cpp.s

average_videos.o: average_videos.cpp.o
.PHONY : average_videos.o

# target to build an object file
average_videos.cpp.o:
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/average_videos.cpp.o
.PHONY : average_videos.cpp.o

average_videos.i: average_videos.cpp.i
.PHONY : average_videos.i

# target to preprocess a source file
average_videos.cpp.i:
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/average_videos.cpp.i
.PHONY : average_videos.cpp.i

average_videos.s: average_videos.cpp.s
.PHONY : average_videos.s

# target to generate assembly for a file
average_videos.cpp.s:
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/average_videos.cpp.s
.PHONY : average_videos.cpp.s

base_camera_server.o: base_camera_server.cpp.o
.PHONY : base_camera_server.o

# target to build an object file
base_camera_server.cpp.o:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/base_camera_server.cpp.o
.PHONY : base_camera_server.cpp.o

base_camera_server.i: base_camera_server.cpp.i
.PHONY : base_camera_server.i

# target to preprocess a source file
base_camera_server.cpp.i:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/base_camera_server.cpp.i
.PHONY : base_camera_server.cpp.i

base_camera_server.s: base_camera_server.cpp.s
.PHONY : base_camera_server.s

# target to generate assembly for a file
base_camera_server.cpp.s:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/base_camera_server.cpp.s
.PHONY : base_camera_server.cpp.s

check_found_spots.o: check_found_spots.cpp.o
.PHONY : check_found_spots.o

# target to build an object file
check_found_spots.cpp.o:
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/check_found_spots.cpp.o
.PHONY : check_found_spots.cpp.o

check_found_spots.i: check_found_spots.cpp.i
.PHONY : check_found_spots.i

# target to preprocess a source file
check_found_spots.cpp.i:
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/check_found_spots.cpp.i
.PHONY : check_found_spots.cpp.i

check_found_spots.s: check_found_spots.cpp.s
.PHONY : check_found_spots.s

# target to generate assembly for a file
check_found_spots.cpp.s:
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/check_found_spots.cpp.s
.PHONY : check_found_spots.cpp.s

cismm_video_optimizer.o: cismm_video_optimizer.cpp.o
.PHONY : cismm_video_optimizer.o

# target to build an object file
cismm_video_optimizer.cpp.o:
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/cismm_video_optimizer.cpp.o
.PHONY : cismm_video_optimizer.cpp.o

cismm_video_optimizer.i: cismm_video_optimizer.cpp.i
.PHONY : cismm_video_optimizer.i

# target to preprocess a source file
cismm_video_optimizer.cpp.i:
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/cismm_video_optimizer.cpp.i
.PHONY : cismm_video_optimizer.cpp.i

cismm_video_optimizer.s: cismm_video_optimizer.cpp.s
.PHONY : cismm_video_optimizer.s

# target to generate assembly for a file
cismm_video_optimizer.cpp.s:
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/cismm_video_optimizer.cpp.s
.PHONY : cismm_video_optimizer.cpp.s

compare_tracking_files.o: compare_tracking_files.cpp.o
.PHONY : compare_tracking_files.o

# target to build an object file
compare_tracking_files.cpp.o:
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/compare_tracking_files.cpp.o
.PHONY : compare_tracking_files.cpp.o

compare_tracking_files.i: compare_tracking_files.cpp.i
.PHONY : compare_tracking_files.i

# target to preprocess a source file
compare_tracking_files.cpp.i:
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/compare_tracking_files.cpp.i
.PHONY : compare_tracking_files.cpp.i

compare_tracking_files.s: compare_tracking_files.cpp.s
.PHONY : compare_tracking_files.s

# target to generate assembly for a file
compare_tracking_files.cpp.s:
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/compare_tracking_files.cpp.s
.PHONY : compare_tracking_files.cpp.s

csv_to_xml.o: csv_to_xml.cpp.o
.PHONY : csv_to_xml.o

# target to build an object file
csv_to_xml.cpp.o:
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/csv_to_xml.cpp.o
.PHONY : csv_to_xml.cpp.o

csv_to_xml.i: csv_to_xml.cpp.i
.PHONY : csv_to_xml.i

# target to preprocess a source file
csv_to_xml.cpp.i:
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/csv_to_xml.cpp.i
.PHONY : csv_to_xml.cpp.i

csv_to_xml.s: csv_to_xml.cpp.s
.PHONY : csv_to_xml.s

# target to generate assembly for a file
csv_to_xml.cpp.s:
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/csv_to_xml.cpp.s
.PHONY : csv_to_xml.cpp.s

file_list.o: file_list.cpp.o
.PHONY : file_list.o

# target to build an object file
file_list.cpp.o:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_list.cpp.o
.PHONY : file_list.cpp.o

file_list.i: file_list.cpp.i
.PHONY : file_list.i

# target to preprocess a source file
file_list.cpp.i:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_list.cpp.i
.PHONY : file_list.cpp.i

file_list.s: file_list.cpp.s
.PHONY : file_list.s

# target to generate assembly for a file
file_list.cpp.s:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_list.cpp.s
.PHONY : file_list.cpp.s

file_stack_server.o: file_stack_server.cpp.o
.PHONY : file_stack_server.o

# target to build an object file
file_stack_server.cpp.o:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_stack_server.cpp.o
.PHONY : file_stack_server.cpp.o

file_stack_server.i: file_stack_server.cpp.i
.PHONY : file_stack_server.i

# target to preprocess a source file
file_stack_server.cpp.i:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_stack_server.cpp.i
.PHONY : file_stack_server.cpp.i

file_stack_server.s: file_stack_server.cpp.s
.PHONY : file_stack_server.s

# target to generate assembly for a file
file_stack_server.cpp.s:
	$(MAKE) -f CMakeFiles/file_stack_library.dir/build.make CMakeFiles/file_stack_library.dir/file_stack_server.cpp.s
.PHONY : file_stack_server.cpp.s

image_wrapper.o: image_wrapper.cpp.o
.PHONY : image_wrapper.o

# target to build an object file
image_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/image_wrapper.cpp.o
.PHONY : image_wrapper.cpp.o

image_wrapper.i: image_wrapper.cpp.i
.PHONY : image_wrapper.i

# target to preprocess a source file
image_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/image_wrapper.cpp.i
.PHONY : image_wrapper.cpp.i

image_wrapper.s: image_wrapper.cpp.s
.PHONY : image_wrapper.s

# target to generate assembly for a file
image_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/image_wrapper.cpp.s
.PHONY : image_wrapper.cpp.s

invert_image.o: invert_image.cpp.o
.PHONY : invert_image.o

# target to build an object file
invert_image.cpp.o:
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/invert_image.cpp.o
.PHONY : invert_image.cpp.o

invert_image.i: invert_image.cpp.i
.PHONY : invert_image.i

# target to preprocess a source file
invert_image.cpp.i:
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/invert_image.cpp.i
.PHONY : invert_image.cpp.i

invert_image.s: invert_image.cpp.s
.PHONY : invert_image.s

# target to generate assembly for a file
invert_image.cpp.s:
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/invert_image.cpp.s
.PHONY : invert_image.cpp.s

make_compression_video.o: make_compression_video.cpp.o
.PHONY : make_compression_video.o

# target to build an object file
make_compression_video.cpp.o:
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/make_compression_video.cpp.o
.PHONY : make_compression_video.cpp.o

make_compression_video.i: make_compression_video.cpp.i
.PHONY : make_compression_video.i

# target to preprocess a source file
make_compression_video.cpp.i:
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/make_compression_video.cpp.i
.PHONY : make_compression_video.cpp.i

make_compression_video.s: make_compression_video.cpp.s
.PHONY : make_compression_video.s

# target to generate assembly for a file
make_compression_video.cpp.s:
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/make_compression_video.cpp.s
.PHONY : make_compression_video.cpp.s

make_moving_spot_video.o: make_moving_spot_video.cpp.o
.PHONY : make_moving_spot_video.o

# target to build an object file
make_moving_spot_video.cpp.o:
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/make_moving_spot_video.cpp.o
.PHONY : make_moving_spot_video.cpp.o

make_moving_spot_video.i: make_moving_spot_video.cpp.i
.PHONY : make_moving_spot_video.i

# target to preprocess a source file
make_moving_spot_video.cpp.i:
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/make_moving_spot_video.cpp.i
.PHONY : make_moving_spot_video.cpp.i

make_moving_spot_video.s: make_moving_spot_video.cpp.s
.PHONY : make_moving_spot_video.s

# target to generate assembly for a file
make_moving_spot_video.cpp.s:
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/make_moving_spot_video.cpp.s
.PHONY : make_moving_spot_video.cpp.s

make_multi_spot_test.o: make_multi_spot_test.cpp.o
.PHONY : make_multi_spot_test.o

# target to build an object file
make_multi_spot_test.cpp.o:
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/make_multi_spot_test.cpp.o
.PHONY : make_multi_spot_test.cpp.o

make_multi_spot_test.i: make_multi_spot_test.cpp.i
.PHONY : make_multi_spot_test.i

# target to preprocess a source file
make_multi_spot_test.cpp.i:
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/make_multi_spot_test.cpp.i
.PHONY : make_multi_spot_test.cpp.i

make_multi_spot_test.s: make_multi_spot_test.cpp.s
.PHONY : make_multi_spot_test.s

# target to generate assembly for a file
make_multi_spot_test.cpp.s:
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/make_multi_spot_test.cpp.s
.PHONY : make_multi_spot_test.cpp.s

make_test_image.o: make_test_image.cpp.o
.PHONY : make_test_image.o

# target to build an object file
make_test_image.cpp.o:
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/make_test_image.cpp.o
.PHONY : make_test_image.cpp.o

make_test_image.i: make_test_image.cpp.i
.PHONY : make_test_image.i

# target to preprocess a source file
make_test_image.cpp.i:
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/make_test_image.cpp.i
.PHONY : make_test_image.cpp.i

make_test_image.s: make_test_image.cpp.s
.PHONY : make_test_image.s

# target to generate assembly for a file
make_test_image.cpp.s:
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/make_test_image.cpp.s
.PHONY : make_test_image.cpp.s

ppm.o: ppm.C.o
.PHONY : ppm.o

# target to build an object file
ppm.C.o:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/ppm.C.o
.PHONY : ppm.C.o

ppm.i: ppm.C.i
.PHONY : ppm.i

# target to preprocess a source file
ppm.C.i:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/ppm.C.i
.PHONY : ppm.C.i

ppm.s: ppm.C.s
.PHONY : ppm.s

# target to generate assembly for a file
ppm.C.s:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/ppm.C.s
.PHONY : ppm.C.s

raw_file_server.o: raw_file_server.cpp.o
.PHONY : raw_file_server.o

# target to build an object file
raw_file_server.cpp.o:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/raw_file_server.cpp.o
.PHONY : raw_file_server.cpp.o

raw_file_server.i: raw_file_server.cpp.i
.PHONY : raw_file_server.i

# target to preprocess a source file
raw_file_server.cpp.i:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/raw_file_server.cpp.i
.PHONY : raw_file_server.cpp.i

raw_file_server.s: raw_file_server.cpp.s
.PHONY : raw_file_server.s

# target to generate assembly for a file
raw_file_server.cpp.s:
	$(MAKE) -f CMakeFiles/base_camera_server_library.dir/build.make CMakeFiles/base_camera_server_library.dir/raw_file_server.cpp.s
.PHONY : raw_file_server.cpp.s

spot_math.o: spot_math.cpp.o
.PHONY : spot_math.o

# target to build an object file
spot_math.cpp.o:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_math.cpp.o
.PHONY : spot_math.cpp.o

spot_math.i: spot_math.cpp.i
.PHONY : spot_math.i

# target to preprocess a source file
spot_math.cpp.i:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_math.cpp.i
.PHONY : spot_math.cpp.i

spot_math.s: spot_math.cpp.s
.PHONY : spot_math.s

# target to generate assembly for a file
spot_math.cpp.s:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_math.cpp.s
.PHONY : spot_math.cpp.s

spot_tracker.o: spot_tracker.cpp.o
.PHONY : spot_tracker.o

# target to build an object file
spot_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_tracker.cpp.o
.PHONY : spot_tracker.cpp.o

spot_tracker.i: spot_tracker.cpp.i
.PHONY : spot_tracker.i

# target to preprocess a source file
spot_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_tracker.cpp.i
.PHONY : spot_tracker.cpp.i

spot_tracker.s: spot_tracker.cpp.s
.PHONY : spot_tracker.s

# target to generate assembly for a file
spot_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/spot_tracker_library.dir/build.make CMakeFiles/spot_tracker_library.dir/spot_tracker.cpp.s
.PHONY : spot_tracker.cpp.s

stocc_random_number_generator/mersenne.o: stocc_random_number_generator/mersenne.cpp.o
.PHONY : stocc_random_number_generator/mersenne.o

# target to build an object file
stocc_random_number_generator/mersenne.cpp.o:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/mersenne.cpp.o
.PHONY : stocc_random_number_generator/mersenne.cpp.o

stocc_random_number_generator/mersenne.i: stocc_random_number_generator/mersenne.cpp.i
.PHONY : stocc_random_number_generator/mersenne.i

# target to preprocess a source file
stocc_random_number_generator/mersenne.cpp.i:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/mersenne.cpp.i
.PHONY : stocc_random_number_generator/mersenne.cpp.i

stocc_random_number_generator/mersenne.s: stocc_random_number_generator/mersenne.cpp.s
.PHONY : stocc_random_number_generator/mersenne.s

# target to generate assembly for a file
stocc_random_number_generator/mersenne.cpp.s:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/mersenne.cpp.s
.PHONY : stocc_random_number_generator/mersenne.cpp.s

stocc_random_number_generator/stoc1.o: stocc_random_number_generator/stoc1.cpp.o
.PHONY : stocc_random_number_generator/stoc1.o

# target to build an object file
stocc_random_number_generator/stoc1.cpp.o:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/stoc1.cpp.o
.PHONY : stocc_random_number_generator/stoc1.cpp.o

stocc_random_number_generator/stoc1.i: stocc_random_number_generator/stoc1.cpp.i
.PHONY : stocc_random_number_generator/stoc1.i

# target to preprocess a source file
stocc_random_number_generator/stoc1.cpp.i:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/stoc1.cpp.i
.PHONY : stocc_random_number_generator/stoc1.cpp.i

stocc_random_number_generator/stoc1.s: stocc_random_number_generator/stoc1.cpp.s
.PHONY : stocc_random_number_generator/stoc1.s

# target to generate assembly for a file
stocc_random_number_generator/stoc1.cpp.s:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/stoc1.cpp.s
.PHONY : stocc_random_number_generator/stoc1.cpp.s

stocc_random_number_generator/userintf.o: stocc_random_number_generator/userintf.cpp.o
.PHONY : stocc_random_number_generator/userintf.o

# target to build an object file
stocc_random_number_generator/userintf.cpp.o:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/userintf.cpp.o
.PHONY : stocc_random_number_generator/userintf.cpp.o

stocc_random_number_generator/userintf.i: stocc_random_number_generator/userintf.cpp.i
.PHONY : stocc_random_number_generator/userintf.i

# target to preprocess a source file
stocc_random_number_generator/userintf.cpp.i:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/userintf.cpp.i
.PHONY : stocc_random_number_generator/userintf.cpp.i

stocc_random_number_generator/userintf.s: stocc_random_number_generator/userintf.cpp.s
.PHONY : stocc_random_number_generator/userintf.s

# target to generate assembly for a file
stocc_random_number_generator/userintf.cpp.s:
	$(MAKE) -f CMakeFiles/stocc_random_number_generator_library.dir/build.make CMakeFiles/stocc_random_number_generator_library.dir/stocc_random_number_generator/userintf.cpp.s
.PHONY : stocc_random_number_generator/userintf.cpp.s

swap_ppm_lines.o: swap_ppm_lines.cpp.o
.PHONY : swap_ppm_lines.o

# target to build an object file
swap_ppm_lines.cpp.o:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/swap_ppm_lines.cpp.o
.PHONY : swap_ppm_lines.cpp.o

swap_ppm_lines.i: swap_ppm_lines.cpp.i
.PHONY : swap_ppm_lines.i

# target to preprocess a source file
swap_ppm_lines.cpp.i:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/swap_ppm_lines.cpp.i
.PHONY : swap_ppm_lines.cpp.i

swap_ppm_lines.s: swap_ppm_lines.cpp.s
.PHONY : swap_ppm_lines.s

# target to generate assembly for a file
swap_ppm_lines.cpp.s:
	$(MAKE) -f CMakeFiles/swap_ppm_lines.dir/build.make CMakeFiles/swap_ppm_lines.dir/swap_ppm_lines.cpp.s
.PHONY : swap_ppm_lines.cpp.s

test_spot_tracker.o: test_spot_tracker.cpp.o
.PHONY : test_spot_tracker.o

# target to build an object file
test_spot_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/test_spot_tracker.cpp.o
.PHONY : test_spot_tracker.cpp.o

test_spot_tracker.i: test_spot_tracker.cpp.i
.PHONY : test_spot_tracker.i

# target to preprocess a source file
test_spot_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/test_spot_tracker.cpp.i
.PHONY : test_spot_tracker.cpp.i

test_spot_tracker.s: test_spot_tracker.cpp.s
.PHONY : test_spot_tracker.s

# target to generate assembly for a file
test_spot_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/test_spot_tracker.cpp.s
.PHONY : test_spot_tracker.cpp.s

thread.o: thread.cpp.o
.PHONY : thread.o

# target to build an object file
thread.cpp.o:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/thread.cpp.o
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/thread.cpp.o
.PHONY : thread.cpp.o

thread.i: thread.cpp.i
.PHONY : thread.i

# target to preprocess a source file
thread.cpp.i:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/thread.cpp.i
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/thread.cpp.i
.PHONY : thread.cpp.i

thread.s: thread.cpp.s
.PHONY : thread.s

# target to generate assembly for a file
thread.cpp.s:
	$(MAKE) -f CMakeFiles/Panoptes_Stage_Control.dir/build.make CMakeFiles/Panoptes_Stage_Control.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/add_noise_to_image.dir/build.make CMakeFiles/add_noise_to_image.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/airy_maker.dir/build.make CMakeFiles/airy_maker.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/average_videos.dir/build.make CMakeFiles/average_videos.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/check_found_spots.dir/build.make CMakeFiles/check_found_spots.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/cismm_video_optimizer.dir/build.make CMakeFiles/cismm_video_optimizer.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/compare_tracking_files.dir/build.make CMakeFiles/compare_tracking_files.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/csv_to_xml.dir/build.make CMakeFiles/csv_to_xml.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/invert_image.dir/build.make CMakeFiles/invert_image.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/make_compression_video.dir/build.make CMakeFiles/make_compression_video.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/make_moving_spot_video.dir/build.make CMakeFiles/make_moving_spot_video.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/make_multi_spot_test.dir/build.make CMakeFiles/make_multi_spot_test.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/make_test_image.dir/build.make CMakeFiles/make_test_image.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/test_spot_tracker.dir/build.make CMakeFiles/test_spot_tracker.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/thread.cpp.s
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/thread.cpp.s
.PHONY : thread.cpp.s

video_imager_server.o: video_imager_server.cpp.o
.PHONY : video_imager_server.o

# target to build an object file
video_imager_server.cpp.o:
	$(MAKE) -f CMakeFiles/video_imager_server.dir/build.make CMakeFiles/video_imager_server.dir/video_imager_server.cpp.o
.PHONY : video_imager_server.cpp.o

video_imager_server.i: video_imager_server.cpp.i
.PHONY : video_imager_server.i

# target to preprocess a source file
video_imager_server.cpp.i:
	$(MAKE) -f CMakeFiles/video_imager_server.dir/build.make CMakeFiles/video_imager_server.dir/video_imager_server.cpp.i
.PHONY : video_imager_server.cpp.i

video_imager_server.s: video_imager_server.cpp.s
.PHONY : video_imager_server.s

# target to generate assembly for a file
video_imager_server.cpp.s:
	$(MAKE) -f CMakeFiles/video_imager_server.dir/build.make CMakeFiles/video_imager_server.dir/video_imager_server.cpp.s
.PHONY : video_imager_server.cpp.s

video_spot_tracker.o: video_spot_tracker.cpp.o
.PHONY : video_spot_tracker.o

# target to build an object file
video_spot_tracker.cpp.o:
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/video_spot_tracker.cpp.o
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/video_spot_tracker.cpp.o
.PHONY : video_spot_tracker.cpp.o

video_spot_tracker.i: video_spot_tracker.cpp.i
.PHONY : video_spot_tracker.i

# target to preprocess a source file
video_spot_tracker.cpp.i:
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/video_spot_tracker.cpp.i
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/video_spot_tracker.cpp.i
.PHONY : video_spot_tracker.cpp.i

video_spot_tracker.s: video_spot_tracker.cpp.s
.PHONY : video_spot_tracker.s

# target to generate assembly for a file
video_spot_tracker.cpp.s:
	$(MAKE) -f CMakeFiles/video_spot_tracker.dir/build.make CMakeFiles/video_spot_tracker.dir/video_spot_tracker.cpp.s
	$(MAKE) -f CMakeFiles/video_spot_tracker_nogui.dir/build.make CMakeFiles/video_spot_tracker_nogui.dir/video_spot_tracker.cpp.s
.PHONY : video_spot_tracker.cpp.s

xml_tracking_compare.o: xml_tracking_compare.cpp.o
.PHONY : xml_tracking_compare.o

# target to build an object file
xml_tracking_compare.cpp.o:
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/xml_tracking_compare.cpp.o
.PHONY : xml_tracking_compare.cpp.o

xml_tracking_compare.i: xml_tracking_compare.cpp.i
.PHONY : xml_tracking_compare.i

# target to preprocess a source file
xml_tracking_compare.cpp.i:
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/xml_tracking_compare.cpp.i
.PHONY : xml_tracking_compare.cpp.i

xml_tracking_compare.s: xml_tracking_compare.cpp.s
.PHONY : xml_tracking_compare.s

# target to generate assembly for a file
xml_tracking_compare.cpp.s:
	$(MAKE) -f CMakeFiles/xml_tracking_compare.dir/build.make CMakeFiles/xml_tracking_compare.dir/xml_tracking_compare.cpp.s
.PHONY : xml_tracking_compare.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Panoptes_Stage_Control"
	@echo "... Tcl_Linkvar"
	@echo "... add_noise_to_image"
	@echo "... airy_maker"
	@echo "... average_videos"
	@echo "... base_camera_server_library"
	@echo "... check_found_spots"
	@echo "... cismm_video_optimizer"
	@echo "... compare_tracking_files"
	@echo "... csv_to_xml"
	@echo "... edit_cache"
	@echo "... file_stack_library"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... invert_image"
	@echo "... list_install_components"
	@echo "... make_compression_video"
	@echo "... make_moving_spot_video"
	@echo "... make_multi_spot_test"
	@echo "... make_test_image"
	@echo "... rebuild_cache"
	@echo "... spot_tracker_library"
	@echo "... stocc_random_number_generator_library"
	@echo "... swap_ppm_lines"
	@echo "... test_spot_tracker"
	@echo "... video_imager_server"
	@echo "... video_spot_tracker"
	@echo "... video_spot_tracker_nogui"
	@echo "... vrpn_imager_library"
	@echo "... xml_tracking_compare"
	@echo "... Panoptes_Stage_Control.o"
	@echo "... Panoptes_Stage_Control.i"
	@echo "... Panoptes_Stage_Control.s"
	@echo "... Tcl_Linkvar.o"
	@echo "... Tcl_Linkvar.i"
	@echo "... Tcl_Linkvar.s"
	@echo "... VRPN_Imager_camera_server.o"
	@echo "... VRPN_Imager_camera_server.i"
	@echo "... VRPN_Imager_camera_server.s"
	@echo "... add_noise_to_image.o"
	@echo "... add_noise_to_image.i"
	@echo "... add_noise_to_image.s"
	@echo "... airy_maker.o"
	@echo "... airy_maker.i"
	@echo "... airy_maker.s"
	@echo "... average_videos.o"
	@echo "... average_videos.i"
	@echo "... average_videos.s"
	@echo "... base_camera_server.o"
	@echo "... base_camera_server.i"
	@echo "... base_camera_server.s"
	@echo "... check_found_spots.o"
	@echo "... check_found_spots.i"
	@echo "... check_found_spots.s"
	@echo "... cismm_video_optimizer.o"
	@echo "... cismm_video_optimizer.i"
	@echo "... cismm_video_optimizer.s"
	@echo "... compare_tracking_files.o"
	@echo "... compare_tracking_files.i"
	@echo "... compare_tracking_files.s"
	@echo "... csv_to_xml.o"
	@echo "... csv_to_xml.i"
	@echo "... csv_to_xml.s"
	@echo "... file_list.o"
	@echo "... file_list.i"
	@echo "... file_list.s"
	@echo "... file_stack_server.o"
	@echo "... file_stack_server.i"
	@echo "... file_stack_server.s"
	@echo "... image_wrapper.o"
	@echo "... image_wrapper.i"
	@echo "... image_wrapper.s"
	@echo "... invert_image.o"
	@echo "... invert_image.i"
	@echo "... invert_image.s"
	@echo "... make_compression_video.o"
	@echo "... make_compression_video.i"
	@echo "... make_compression_video.s"
	@echo "... make_moving_spot_video.o"
	@echo "... make_moving_spot_video.i"
	@echo "... make_moving_spot_video.s"
	@echo "... make_multi_spot_test.o"
	@echo "... make_multi_spot_test.i"
	@echo "... make_multi_spot_test.s"
	@echo "... make_test_image.o"
	@echo "... make_test_image.i"
	@echo "... make_test_image.s"
	@echo "... ppm.o"
	@echo "... ppm.i"
	@echo "... ppm.s"
	@echo "... raw_file_server.o"
	@echo "... raw_file_server.i"
	@echo "... raw_file_server.s"
	@echo "... spot_math.o"
	@echo "... spot_math.i"
	@echo "... spot_math.s"
	@echo "... spot_tracker.o"
	@echo "... spot_tracker.i"
	@echo "... spot_tracker.s"
	@echo "... stocc_random_number_generator/mersenne.o"
	@echo "... stocc_random_number_generator/mersenne.i"
	@echo "... stocc_random_number_generator/mersenne.s"
	@echo "... stocc_random_number_generator/stoc1.o"
	@echo "... stocc_random_number_generator/stoc1.i"
	@echo "... stocc_random_number_generator/stoc1.s"
	@echo "... stocc_random_number_generator/userintf.o"
	@echo "... stocc_random_number_generator/userintf.i"
	@echo "... stocc_random_number_generator/userintf.s"
	@echo "... swap_ppm_lines.o"
	@echo "... swap_ppm_lines.i"
	@echo "... swap_ppm_lines.s"
	@echo "... test_spot_tracker.o"
	@echo "... test_spot_tracker.i"
	@echo "... test_spot_tracker.s"
	@echo "... thread.o"
	@echo "... thread.i"
	@echo "... thread.s"
	@echo "... video_imager_server.o"
	@echo "... video_imager_server.i"
	@echo "... video_imager_server.s"
	@echo "... video_spot_tracker.o"
	@echo "... video_spot_tracker.i"
	@echo "... video_spot_tracker.s"
	@echo "... xml_tracking_compare.o"
	@echo "... xml_tracking_compare.i"
	@echo "... xml_tracking_compare.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

